### ISSUE TITLE
Test suite fails completely on openSUSE/Tumbleweed

### ISSUE THREAD

**Issue by mcepl** [jaraco/tempora#6]
```
[    5s] + PYTHONPATH=:/home/abuild/rpmbuild/BUILDROOT/python-tempora-1.14-0.x86_64/usr/lib/pyth
on2.7/site-packages
[    5s] + python2 -mpytest --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy
3 -v tests
[    5s] ============================= test session starts ==============================
[    5s] platform linux2 -- Python 2.7.15, pytest-3.10.1, py-1.8.0, pluggy-0.9.0 -- /usr/bin/pyt
hon2
[    5s] cachedir: .pytest_cache
[    5s] rootdir: /home/abuild/rpmbuild/BUILD/tempora-1.14, inifile: pytest.ini
[    5s] plugins: flake8-1.0.4, backports.unittest-mock-1.4
[    5s] collecting ... INTERNALERROR> Traceback (most recent call last):
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/main.py", line 184, in
wrap_session
[    5s] INTERNALERROR>     session.exitstatus = doit(config, session) or 0
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/main.py", line 223, in
_main
[    5s] INTERNALERROR>     config.hook.pytest_collection(session=session)
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in
__call__
[    5s] INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 68, in
 _hookexec
[    5s] INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 62, in
 <lambda>
[    5s] INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else Fals
e,
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 208, i
n _multicall
[    5s] INTERNALERROR>     return outcome.get_result()
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 81, in
 get_result
[    5s] INTERNALERROR>     _reraise(*ex)  # noqa
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 187, i
n _multicall
[    5s] INTERNALERROR>     res = hook_impl.function(*args)
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/main.py", line 233, in
pytest_collection
[    5s] INTERNALERROR>     return session.perform_collect()
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/_pytest/main.py", line 434, in
perform_collect
[    5s] INTERNALERROR>     session=self, config=self.config, items=items
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in
__call__
[    5s] INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 68, in
 _hookexec
[    5s] INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 62, in
 <lambda>
[    5s] INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else Fals
e,
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 208, i
n _multicall
[    5s] INTERNALERROR>     return outcome.get_result()
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 81, in
 get_result
[    5s] INTERNALERROR>     _reraise(*ex)  # noqa
[    5s] INTERNALERROR>   File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 187, i
n _multicall
[    5s] INTERNALERROR>     res = hook_impl.function(*args)
[    5s] INTERNALERROR>   File "/home/abuild/rpmbuild/BUILD/tempora-1.14/conftest.py", line 6, i
n pytest_collection_modifyitems
[    5s] INTERNALERROR>     remove_parse_timedelta(items)
[    5s] INTERNALERROR>   File "/home/abuild/rpmbuild/BUILD/tempora-1.14/conftest.py", line 17,
in remove_parse_timedelta
[    5s] INTERNALERROR>     del items[names.index('tempora.parse_timedelta')]
[    5s] INTERNALERROR> ValueError: 'tempora.parse_timedelta' is not in list
[    5s]
[    5s] =========================== 2 error in 0.06 seconds ============================
[    5s] error: Bad exit status from /var/tmp/rpm-tmp.ScMEAr (%check)
[    5s]
[    5s]
[    5s] RPM build errors:
[    5s]     Bad exit status from /var/tmp/rpm-tmp.ScMEAr (%check)
[    5s]
[    5s] milic failed "build python-tempora.spec" at Thu Mar 14 17:20:23 UTC 2019.
[    5s]

The buildroot was: /var/tmp/build-root/openSUSE_Tumbleweed-x86_64
python-tempora$
```
This is complete [build log](https://github.com/jaraco/tempora/files/2967918/log.txt)

**Comment by jayvdb** [comment]
This was a bug in the packaging.
Fixed in https://build.opensuse.org/request/show/686809
